# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localhandsapp', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sub_total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'Processing'), (4, 'Delivered'), (3, 'On the way'), (1, 'Pending')]),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='localhandsapp.Order'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localhandsapp.Task'),
        ),
    ]
