# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localhandsapp', '0005_auto_20170120_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localhandsapp.Driver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'Delivered'), (2, 'Started'), (1, 'Waiting'), (3, 'On the way')]),
        ),
    ]
