# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localhandsapp', '0006_auto_20170120_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Started'), (4, 'Delivered'), (3, 'On the way')]),
        ),
    ]
